### ISSUE TITLE
map GW Layerout 1

### ISSUE THREAD

**Issue by Az0te** [hutber/tts-map-base#1]
on load  pariah Nexus GW Layerout1 map, gives error Failed to load Model (.obj):  http://http://pastebin.com/raw.php?i=RwY2qFkX

**Comment by Az0te** [comment]
the big ruins are not showin, only the base and the small ruins
thanks

**Comment by hutber** [comment]
Thanks for raising!
Please confirm issue is fixed.

**Comment by Az0te** [comment]
Thanks man, sem error still persits not only on layerout 1 and 7  both failing, tryed unsuscribe mod and disbale cache, nothing, not the only one we are doing a learning champioship and almost all having problems but 3 players was able to load it from 65.  I checked the code and the maps that was giving problems had images allocated on pastebin the others map have a diferent images maybe thats the cause not working but I m not experienced on tts mods so no idea. Hope this was usefull.
Thanks for your effort and for working on the best tts 40k table

**Comment by Az0te** [comment]
ah and 4 also failing , the ones with lighter grounds

**Comment by hutber** [comment]
Ye, effectively all the people who have loaded it previously should be able to still load it up. So thats where those sneaky 3 people come from :D lol

I just tested on a brand new machine and everything is working. 
In theory, you should see errors previously.
Umm I wonder if you have the cached broken version at this point.

Could you try to load up this map:
https://steamcommunity.com/sharedfiles/filedetails/?id=3244120187

This is where the GW maps come from. In theory, these should fail for you too.

**Comment by Az0te** [comment]
Oka let me try, Cache off
![Image](https://github.com/user-attachments/assets/95a4c3c2-df70-4df0-984e-76206f63acfb)

![Image](https://github.com/user-attachments/assets/ef3e6df1-847a-4df6-afd6-c433def77f8d)

![Image](https://github.com/user-attachments/assets/9a67f3e5-30a1-4aa1-a473-f55be7f2c864)

As you see i tryed  also and download the individuals ones that its the same layerout 1 error and same orange ground

![Image](https://github.com/user-attachments/assets/b312219d-8103-42bc-b32e-16b3cb52c4a5)

![Image](https://github.com/user-attachments/assets/299372da-c03b-4500-8707-66bad9c58802)
from the link you sended its working, oka we can use load aditive

tryed to unsuscribe, delete from tabletop, suscribe again but stil not working

![Image](https://github.com/user-attachments/assets/66d5e936-d93a-40cc-8e95-462fddbf7986)

the ground it s orange on the wrong one

**Comment by hutber** [comment]
Ye this confirms:

![Image](https://github.com/user-attachments/assets/04d05f70-63a7-4f19-85cd-00466a66e28f)
You are not loading in the new map for some reason!

And... holy shit, you know what you're not?! I hadn't pushed the latest changes! Christ, sorry about that and thank you for persisting!!

**Comment by Az0te** [comment]
thanks man its working perfect now

![Image](https://github.com/user-attachments/assets/a994cf9a-b65d-47d1-8363-6e5c6412f5f7)

Thanks you for all your hard work and for been so quick

**Comment by Az0te** [comment]
confirmed the other players also working perfect
